import { mkdirSync, readFileSync, writeFileSync, copyFileSync, readdirSync } from 'node:fs';
import path from 'node:path';
import { root, validate, escapeHtml as h } from './catalog.mjs';
import { historyText } from './history.mjs';
const catalog=validate();
if(readFileSync(path.join(root,'HISTORICO.md'),'utf8')!==historyText(catalog))throw Error('Histórico desatualizado. Execute npm run history.');
const output=path.join(root,'dist');mkdirSync(output,{recursive:true});
for(const file of ['styles.css','library.js','favicon.svg','404.html','progress.css','progress.js','progress-model.js','firebase-config.js'])copyFileSync(path.join(root,'site',file),path.join(output,file));
mkdirSync(path.join(output,'assets'),{recursive:true});
for(const file of readdirSync(path.join(root,'site','assets')).filter(file=>/\.(gif|png|mp4|webm|svg)$/i.test(file)))copyFileSync(path.join(root,'site','assets',file),path.join(output,'assets',file));
const levels={iniciante:'Iniciante',intermediario:'Intermediário',avancado:'Avançado'};
const progressPanel=(l,article=false)=>`<section class="progress-panel${article?' article-progress':''}" data-progress-panel data-article="${article}" data-lesson-id="${h(l.id)}" data-quiz="${h(JSON.stringify(l.quiz||null))}" aria-label="Seu progresso"><div class="progress-top"><span class="read-label" data-read-label>Entre para acompanhar sua leitura</span><button class="read-toggle" type="button" data-read-toggle aria-pressed="false" disabled>Marcar como lido</button></div><p class="quiz-label" data-quiz-label>Resultados privados da sua conta</p>${article?'<p class="progress-help">Responder salva o resultado; marcar como lido é uma decisão sua. O desafio é para estudo, sem valor de certificação.</p>':''}</section>`;
const cards=[...catalog.lessons].sort((a,b)=>b.date.localeCompare(a.date)).map(l=>`<article class="lesson" data-topic="${h(l.topic)}"><div class="lesson-meta"><span>${h(catalog.topics.find(t=>t.id===l.topic).name)}</span><span>${h(l.date.split('-').reverse().join('/'))}</span></div><h2><a href="${h(l.url)}">${h(l.title)}</a></h2><p>${h(l.objective)}</p><div class="tags"><span>${levels[l.level]}</span><span>${l.minutes.essential}–${l.minutes.full} min</span></div>${progressPanel(l)}<a class="read" href="${h(l.url)}">Ler edição <span aria-hidden="true">↗</span></a></article>`).join('\n');
const topics=catalog.topics.map(t=>`<button type="button" class="topic" data-filter="${h(t.id)}" aria-pressed="false"><span class="topic-name">${h(t.name)}</span><span class="topic-count">${catalog.lessons.filter(l=>l.topic===t.id).length} ${catalog.lessons.filter(l=>l.topic===t.id).length===1?'edição':'edições'}</span><span class="topic-description">${h(t.description)}</span></button>`).join('\n');
let home=readFileSync(path.join(root,'site/index.html'),'utf8').replace('{{TOPICS}}',topics).replace('{{LESSONS}}',cards).replace('{{COUNT}}',String(catalog.lessons.length));
writeFileSync(path.join(output,'index.html'),home);
for(const lesson of catalog.lessons){const dest=path.join(output,lesson.url);mkdirSync(path.dirname(dest),{recursive:true});let html=readFileSync(path.join(root,lesson.source),'utf8');html=html.replace('</head>','<link rel="icon" type="image/svg+xml" href="../../favicon.svg">\n<link rel="stylesheet" href="../../progress.css"><script type="module" src="../../progress.js"></script>\n<meta name="description" content="'+h(lesson.objective)+'">\n</head>');html=html.replace('<div class="wrap">','<div class="wrap"><div class="sync-bar"><nav aria-label="Biblioteca"><a href="../../index.html">← Biblioteca / '+h(catalog.topics.find(t=>t.id===lesson.topic).name)+'</a></nav><button class="account" id="account" type="button" disabled>Entrar com Google</button></div><p id="sync-status" class="sync-status" role="status">Preparando sincronização…</p>');html=html.replace('<noscript>',progressPanel(lesson,true)+'<noscript>');writeFileSync(dest,html);}
writeFileSync(path.join(output,'catalog.json'),JSON.stringify(catalog,null,2)+'\n');
console.log(`Site gerado em dist/: ${catalog.lessons.length} edição(ões).`);
